services:
  jupyterlab:
    build:
      context: .
      dockerfile: jupyterlab/Dockerfile
    image: custom-jupyter:latest
    container_name: jupyterlab
    hostname: jupyterlab
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    ports:
      - "2222:22" # Open 22 to sshd
    volumes:
      - /home/alex/src/jupyter_work:/home/jovyan/work  # Shared workspace
      - /mnt/gdrive:/home/jovyan/gdrive                # Shared Google Drive mount
      - /home/alex/jupyter_server_data/jupyter_config:/home/jovyan/.jupyter # Shared Settings (Syncs themes, fonts, shortcuts)
      - /home/alex/jupyter_server_data/huggingface_cache:/home/jovyan/.cache/huggingface # Shared Model Cache
      - /home/alex/jupyter_server_data/jetbrains-backend-cache:/home/jovyan/.cache/JetBrains # Shared IDE Cache
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - PYTHONPATH=/home/jovyan/work/jupyterlab
      - SETUPTOOLS_USE_DISTUTILS=stdlib
      - TF_CPP_MIN_LOG_LEVEL=3
      - TF_XLA_FLAGS=--tf_xla_enable_xla_devices=false
      - PYTHONWARNINGS=ignore
    deploy:
      resources:
        limits:
          memory: 55G
        reservations:
          memory: 10G
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  jupyterlab-pytorch:
    build:
      context: .
      dockerfile: jupyterlab.pytorch/Dockerfile
    image: custom-jupyter-pytorch:latest
    container_name: jupyterlab-pytorch
    hostname: jupyterlab-pytorch
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    ports:
      - "2223:22" # Open 22 to sshd
    volumes:
      - /home/alex/src/jupyter_work:/home/jovyan/work
      - /mnt/gdrive:/home/jovyan/gdrive
      - /home/alex/jupyter_server_data/jupyter_config:/home/jovyan/.jupyter
      - /home/alex/jupyter_server_data/huggingface_cache:/home/jovyan/.cache/huggingface
      - /home/alex/jupyter_server_data/jetbrains-backend-cache:/home/jovyan/.cache/JetBrains
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    deploy:
      resources:
        limits:
          memory: 55G
        reservations:
          memory: 10G
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  tensorboard:
    image: custom-jupyter:latest
    container_name: tensorboard
    depends_on:
      - jupyterlab
    command: tensorboard --logdir /home/jovyan/work/logs/fit --bind_all --port 6006
    ports:
      - "6006:6006"
    volumes:
      - /home/alex/src/jupyter_work:/home/jovyan/work
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8888:8888" # Exposes jupyterlab
      - "8889:8889" # Exposes jupyterlab-pytorch
    depends_on:
      - jupyterlab
      - jupyterlab-pytorch

volumes:
  jetbrains-backend-cache:
    driver: local
    driver_opts:
      type: none
      device: /home/alex/jupyter_server_data/jetbrains-backend-cache
      o: bind
