x-jupyter-base: &jupyter-base
  ipc: host
  ulimits:
    memlock: -1
    stack: 67108864
  volumes:
    - jupyter_work:/home/jovyan/work
    - gdrive:/home/jovyan/gdrive
    - jupyter_config:/home/jovyan/.jupyter
    - huggingface_cache:/home/jovyan/.cache/huggingface
    - jetbrains-backend-cache:/home/jovyan/.cache/JetBrains
  environment: &common-env
    JUPYTER_TOKEN: ${JUPYTER_TOKEN:?JUPYTER_TOKEN is not set. Please define it in a .env file.}
    HF_TOKEN: ${HF_TOKEN:?HF_TOKEN is not set. Please define it in a .env file.}
    GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT:-}
    PYTHONPATH: /home/jovyan/work/jupyterlab
    SETUPTOOLS_USE_DISTUTILS: stdlib
    PYTHONWARNINGS: ignore
  deploy:
    resources:
      limits:
        memory: 55G
      reservations:
        memory: 10G
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

services:
  jupyterlab:
    <<: *jupyter-base
    build:
      context: .
      dockerfile: jupyterlab/Dockerfile
    image: custom-jupyter:latest
    container_name: jupyterlab
    hostname: jupyterlab
    ports:
      - "2222:22" # Open 22 to sshd
    environment:
      <<: *common-env
      TF_CPP_MIN_LOG_LEVEL: 3
      TF_XLA_FLAGS: --tf_xla_enable_xla_devices=false

  jupyterlab-pytorch:
    <<: *jupyter-base
    build:
      context: .
      dockerfile: jupyterlab.pytorch/Dockerfile
    image: custom-jupyter-pytorch:latest
    container_name: jupyterlab-pytorch
    hostname: jupyterlab-pytorch
    ports:
      - "2223:22" # Open 22 to sshd

  tensorboard:
    image: custom-jupyter:latest
    container_name: tensorboard
    depends_on:
      - jupyterlab
    command: tensorboard --logdir /home/jovyan/work/logs/fit --bind_all --port 6006
    ports:
      - "6006:6006"
    volumes:
      - jupyter_work:/home/jovyan/work
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8888:8888" # Exposes jupyterlab
      - "8889:8889" # Exposes jupyterlab-pytorch
    depends_on:
      - jupyterlab
      - jupyterlab-pytorch

volumes:
  jupyter_work:
    driver: local
    driver_opts:
      type: none
      device: /home/alex/src/jupyter_work
      o: bind
  gdrive:
    driver: local
    driver_opts:
      type: none
      device: /mnt/gdrive
      o: bind
  jupyter_config:
    driver: local
    driver_opts:
      type: none
      device: /home/alex/jupyter_server_data/jupyter_config
      o: bind
  huggingface_cache:
    driver: local
    driver_opts:
      type: none
      device: /home/alex/jupyter_server_data/huggingface_cache
      o: bind
  jetbrains-backend-cache:
    driver: local
    driver_opts:
      type: none
      device: /home/alex/jupyter_server_data/jetbrains-backend-cache
      o: bind
